### PR TITLE
Fix go version, correct type

### PR DESCRIPTION
**Pull request by cuongquachc88**
- Fix go version for build > Dockerfile
- Update 
go env -w GO111MODULE=off
go run build/templates/generate.go $coin
go env -w GO111MODULE=auto
from original repository to build_deb.sh
- Include the wrong types from https://github.com/mihneadb

### CODE REVIEW

**Comment by feshchenkod** [comment]
I only managed to compile your code, thanks for sharing. Could you help me why the service is not starting? there is nothing on the node other than this service, so I don’t understand what the conflict might be.
```
Nov 23 05:30:38 blockbook-bsc systemd[1]: Started Blockbook daemon (BSC).
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: 2021/11/23 05:30:38 WARNING: proto: file "tx.proto" is already registered
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: A future release will panic on registration conflicts. See:
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: 2021/11/23 05:30:38 WARNING: proto: message eth.ProtoCompleteTransaction is already registered
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: A future release will panic on registration conflicts. See:
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: 2021/11/23 05:30:38 WARNING: proto: message eth.ProtoCompleteTransaction.TxType is already registered
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: A future release will panic on registration conflicts. See:
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: 2021/11/23 05:30:38 WARNING: proto: message eth.ProtoCompleteTransaction.ReceiptType is already registered
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: A future release will panic on registration conflicts. See:
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: 2021/11/23 05:30:38 WARNING: proto: message eth.ProtoCompleteTransaction.ReceiptType.LogType is already registered
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: A future release will panic on registration conflicts. See:
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: 2021/11/23 05:30:38 WARNING: proto: file "tx.proto" is already registered
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: A future release will panic on registration conflicts. See:
Nov 23 05:30:38 blockbook-bsc blockbook[43460]: https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
Nov 23 05:30:42 blockbook-bsc systemd[1]: blockbook-bsc.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

**Comment by feshchenkod** [comment]
I managed to compile packages only from your code, thanks! Could you help with this error please?
`rpc: websocket: bad handshake (HTTP status 200 OK) Retrying...`
This error is spam and the service constantly restarting. rcp available and I already tried to change it. Blockbook synced about 11500000 blocks (sync slowed down after ~9500000 block) and now crashing.

**Comment by feshchenkod** [comment]
I managed to compile packages only from your code, thanks! Could you help with this error please?
`panic: runtime error: slice bounds out of range [:12196040594413952182] with length 384`
This error is spam and the service constantly restarting. rcp available and I already tried to change it. Blockbook synced about 11500000 blocks (sync slowed down after ~9500000 block) and now crashing.

```
blockbook[32039]: panic: runtime error: slice bounds out of range [:12196040594413952182] with length 384
blockbook[32039]: goroutine 150 [running]:
blockbook[32039]: github.com/trezor/blockbook/bchain/coins/bsc.parseErc20StringProperty(0xc0267f0720, 0x14, 0x30, 0xc040773042, 0x180, 0xc040773040, 0x182)
blockbook[32039]:         /go/src/github.com/trezor/blockbook/bchain/coins/bsc/erc20.go:418 +0x565
blockbook[32039]: github.com/trezor/blockbook/bchain/coins/bsc.(*EthereumRPC).EthereumTypeGetErc20ContractInfo(0xc00016e120, 0xc0267f0720, 0x14, 0x30, 0x28, 0x30, 0
blockbook[32039]:         /go/src/github.com/trezor/blockbook/bchain/coins/bsc/erc20.go:472 +0x329
blockbook[32039]: github.com/trezor/blockbook/bchain/coins.(*blockChainWithMetrics).EthereumTypeGetErc20ContractInfo(0xc000284060, 0xc0267f0720, 0x14, 0x30, 0x0, 0x
blockbook[32039]:         /go/src/github.com/trezor/blockbook/bchain/coins/blockchain.go:312 +0xd4
blockbook[32039]: github.com/trezor/blockbook/db.(*RocksDB).storeNewERC20Contracts(0xc00017a1e0, 0xc00074fc78, 0xc01d624270, 0x1, 0x1, 0x0, 0x0)
blockbook[32039]:         /go/src/github.com/trezor/blockbook/db/rocksdb_ethereumtype.go:60 +0xf1
blockbook[32039]: github.com/trezor/blockbook/db.(*BulkConnect).storeBulkAddresses(0xc000286370, 0xc00074fc78, 0x1f87ec0, 0x20)
blockbook[32039]:         /go/src/github.com/trezor/blockbook/db/bulkconnect.go:167 +0x185
blockbook[32039]: github.com/trezor/blockbook/db.(*BulkConnect).connectBlockBscType(0xc000286370, 0xc0004ac1c0, 0x0, 0x0, 0x0)
blockbook[32039]:         /go/src/github.com/trezor/blockbook/db/bulkconnect.go:317 +0x425
blockbook[32039]: github.com/trezor/blockbook/db.(*BulkConnect).ConnectBlock(0xc000286370, 0xc0004ac1c0, 0x0, 0x0, 0x2)
blockbook[32039]:         /go/src/github.com/trezor/blockbook/db/bulkconnect.go:411 +0x65
blockbook[32039]: github.com/trezor/blockbook/db.(*SyncWorker).ConnectBlocksParallel.func1()
blockbook[32039]:         /go/src/github.com/trezor/blockbook/db/sync.go:273 +0x2c5
blockbook[32039]: created by github.com/trezor/blockbook/db.(*SyncWorker).ConnectBlocksParallel
blockbook[32039]:         /go/src/github.com/trezor/blockbook/db/sync.go:324 +0x3cb
systemd[1]: blockbook-bsc.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: blockbook-bsc.service: Failed with result 'exit-code'.
systemd[1]: blockbook-bsc.service: Service RestartSec=100ms expired, scheduling restart.
```

**Comment by cuongquachc88** [comment]
> panic: runtime error: slice bounds out of range

Do you install go in your server ? Ping me cuongquach2911@outlook.com, we will discuss further more for your case

**Comment by feshchenkod** [comment]
sent you an email. started to sync new node and somewhere at the same height (~11500000 blocks) the service began to crash again...

**Pull request closed without merging**
